;******************************************************************************
;**                                   Defines                                **
;******************************************************************************

BUTTON_A		EQU %00000001
BUTTON_B		EQU %00000010
BUTTON_SELECT	EQU %00000100
BUTTON_START	EQU %00001000
BUTTON_RIGHT	EQU %00010000
BUTTON_LEFT 	EQU %00100000
BUTTON_UP		EQU %01000000
BUTTON_DOWN		EQU %10000000
