; GLOBAL_BLOCKS.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 16
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Blocks", ROM0

; Start of tile array.
Global_Blocks::
DB $FF,$FF,$FF,$81,$FF,$81,$E7,$99
DB $E7,$99,$FF,$81,$FF,$81,$FF,$FF
DB $FF,$FF,$81,$81,$BD,$81,$A5,$99
DB $A5,$99,$BD,$81,$81,$81,$FF,$FF
DB $FF,$FF,$FF,$81,$C3,$BD,$DB,$BD
DB $DB,$BD,$C3,$BD,$FF,$81,$FF,$FF
DB $FF,$FF,$81,$81,$BD,$81,$BD,$99
DB $BD,$99,$BD,$81,$81,$81,$FF,$FF
DB $FF,$FF,$FF,$81,$C3,$BD,$C3,$BD
DB $C3,$BD,$C3,$BD,$FF,$81,$FF,$FF
DB $FF,$FF,$81,$81,$BD,$81,$BD,$81
DB $BD,$81,$BD,$81,$81,$81,$FF,$FF
DB $FF,$FF,$FF,$81,$C3,$81,$C3,$99
DB $C3,$99,$C3,$81,$FF,$81,$FF,$FF
DB $FF,$FF,$A5,$81,$FF,$81,$A5,$81
DB $A5,$81,$FF,$81,$A5,$81,$FF,$FF
DB $FF,$FF,$DB,$A5,$81,$FF,$C3,$A5
DB $C3,$A5,$81,$FF,$DB,$A5,$FF,$FF
DB $FF,$FF,$CB,$F3,$89,$93,$E1,$87
DB $87,$E1,$91,$C9,$D3,$CF,$FF,$FF
DB $FF,$FF,$81,$8D,$99,$E5,$A5,$C1
DB $A5,$83,$99,$A7,$81,$B1,$FF,$FF
DB $FF,$FF,$81,$91,$99,$81,$A5,$83
DB $A5,$C1,$99,$81,$81,$89,$FF,$FF
DB $FF,$FF,$81,$81,$A9,$B1,$85,$A1
DB $A1,$85,$95,$8D,$81,$81,$FF,$FF
DB $FF,$FF,$EF,$81,$E7,$89,$C1,$B9
DB $83,$9D,$E7,$91,$F7,$81,$FF,$FF
DB $FF,$FF,$E7,$81,$E7,$99,$81,$A5
DB $81,$A5,$E7,$99,$E7,$81,$FF,$FF
DB $FF,$FF,$C3,$81,$A5,$99,$99,$BD
DB $99,$BD,$A5,$99,$C3,$81,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of GLOBAL_BLOCKS.Z80
