; GLOBAL_TEXTSYMBOLS.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 7
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Text Symbols", ROM0

; Start of tile array.
Global_TextSymbols::
DB $3E,$3E,$3E,$22,$3E,$2E,$38,$28
DB $38,$28,$3E,$2E,$3E,$22,$3E,$3E
DB $7C,$7C,$7C,$44,$7C,$74,$1C,$14
DB $1C,$14,$7C,$74,$7C,$44,$7C,$7C
DB $00,$00,$38,$10,$38,$28,$38,$10
DB $00,$00,$38,$10,$38,$28,$38,$10
DB $00,$00,$66,$24,$7E,$7E,$3C,$24
DB $3C,$24,$7E,$7E,$66,$24,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$7F,$3E,$5D,$63,$7F,$3E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$3C,$18,$3C,$24,$3C,$18
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $18,$00,$3C,$18,$3C,$24,$3C,$3C
DB $38,$10,$38,$28,$38,$28,$38,$28
DB $38,$28,$38,$10,$38,$28,$38,$10

; End of GLOBAL_TEXTSYMBOLS.Z80
