; LETTERS.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 25
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Letters", ROM0

; Start of tile array.
Tiles_Letters::
DB $00,$00,$3E,$1C,$6B,$36,$5D,$6B
DB $7F,$41,$7F,$49,$5D,$6B,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$49
DB $7F,$42,$7F,$49,$5D,$63,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$41
DB $7F,$4E,$7F,$41,$5D,$63,$7F,$3E
DB $00,$00,$7E,$3C,$5B,$66,$7D,$43
DB $7F,$49,$7D,$43,$5B,$66,$7E,$3C
DB $00,$00,$7F,$3E,$5D,$63,$7F,$4E
DB $7A,$46,$7F,$4E,$5D,$63,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$4E
DB $7A,$46,$7E,$4C,$5C,$68,$78,$30
DB $00,$00,$7F,$3E,$5D,$63,$7F,$4E
DB $7D,$4B,$7F,$49,$5D,$63,$7F,$3E
DB $00,$00,$7F,$36,$5D,$6B,$7F,$49
DB $7F,$41,$7F,$49,$5D,$6B,$7F,$36
DB $00,$00,$3E,$1C,$2A,$36,$3E,$22
DB $3E,$22,$3E,$22,$2A,$36,$3E,$1C
DB $00,$00,$3E,$1C,$2A,$36,$3E,$22
DB $7E,$22,$7E,$42,$5A,$66,$7E,$3C
DB $00,$00,$7F,$36,$5D,$6B,$7F,$41
DB $7F,$42,$7F,$41,$5D,$6B,$7F,$36
DB $00,$00,$7C,$38,$54,$6C,$7E,$44
DB $7F,$46,$7F,$41,$5D,$63,$7F,$3E
DB $00,$00,$7F,$36,$5D,$6B,$7F,$41
DB $7F,$49,$7F,$49,$5D,$6B,$7F,$36
DB $00,$00,$7F,$3A,$5D,$67,$7F,$45
DB $7F,$41,$7F,$49,$5D,$6B,$7F,$36
DB $00,$00,$7F,$3E,$5D,$63,$7F,$41
DB $7F,$49,$7F,$41,$5D,$63,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$49
DB $7D,$43,$7F,$4E,$5C,$68,$78,$30
DB $00,$00,$7E,$3C,$5A,$66,$7E,$42
DB $7F,$52,$7F,$41,$5D,$67,$7F,$3A
DB $00,$00,$7F,$3E,$5D,$63,$7F,$49
DB $7F,$41,$7F,$42,$5D,$6B,$7F,$36
DB $00,$00,$7F,$3E,$5D,$63,$7F,$4E
DB $7F,$21,$7F,$59,$5D,$63,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$41
DB $7F,$22,$3E,$22,$2A,$36,$3E,$1C
DB $00,$00,$7F,$36,$5D,$6B,$7F,$49
DB $7F,$49,$7F,$41,$5D,$63,$7F,$3E
DB $00,$00,$7F,$36,$5D,$6B,$7F,$49
DB $7F,$41,$5D,$63,$6B,$36,$3E,$1C
DB $00,$00,$7F,$2A,$55,$7F,$7F,$41
DB $7F,$41,$7F,$22,$2A,$3E,$3E,$14
DB $00,$00,$7F,$36,$5D,$6B,$7F,$41
DB $7F,$22,$7F,$41,$5D,$6B,$7F,$36
DB $00,$00,$7F,$36,$5D,$6B,$7F,$49
DB $7F,$41,$7F,$22,$2A,$36,$3E,$1C
DB $00,$00,$7F,$3E,$5D,$63,$7F,$39
DB $7F,$42,$7F,$4D,$5D,$63,$7F,$3E

; End of LETTERS.Z80
