; NUMBERS.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 9
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Numbers", ROM0

; Start of tile array.
Tiles_Numbers::
DB $00,$00,$7F,$3E,$5D,$63,$7F,$41
DB $7F,$49,$7F,$41,$5D,$63,$7F,$3E
DB $00,$00,$3E,$1C,$6A,$36,$5E,$62
DB $5E,$62,$7E,$22,$2A,$36,$3E,$1C
DB $00,$00,$7F,$3E,$5D,$63,$7F,$39
DB $5F,$62,$7F,$4D,$5D,$63,$7F,$3E
DB $00,$00,$7E,$3C,$5B,$66,$7D,$3B
DB $3F,$22,$3F,$39,$5D,$63,$7F,$3E
DB $00,$00,$7F,$36,$5D,$6B,$7F,$49
DB $5F,$61,$7F,$39,$1D,$0B,$0F,$06
DB $00,$00,$7F,$3E,$5D,$63,$7F,$4E
DB $7F,$21,$7F,$59,$5D,$63,$7F,$3E
DB $00,$00,$78,$30,$5C,$68,$7F,$4E
DB $7D,$43,$7F,$49,$5D,$63,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$41
DB $7F,$39,$1F,$09,$0D,$0B,$0F,$06
DB $00,$00,$7F,$3E,$5D,$63,$7F,$49
DB $7F,$22,$7F,$49,$5D,$63,$7F,$3E
DB $00,$00,$7F,$3E,$5D,$63,$7F,$49
DB $5F,$61,$7F,$39,$1D,$0B,$0F,$06

; End of NUMBERS.Z80
