; PE_CURSORTILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 7
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Cursors", ROM0

; Start of tile array.
PE_CursorTiles::
DB $07,$02,$0D,$05,$19,$09,$11,$11
DB $11,$11,$19,$09,$0D,$05,$07,$02
DB $DB,$E7,$81,$81,$00,$81,$81,$00
DB $81,$00,$00,$81,$81,$81,$DB,$E7
DB $99,$99,$42,$42,$24,$24,$81,$81
DB $81,$81,$24,$24,$42,$42,$99,$99
DB $7E,$7E,$FE,$82,$FE,$BE,$E0,$A0
DB $E0,$A0,$E0,$A0,$E0,$E0,$00,$00
DB $00,$00,$07,$02,$0D,$07,$1B,$0E
DB $F6,$5C,$AC,$F8,$D8,$70,$70,$20
DB $E7,$C3,$BD,$E7,$DB,$7E,$66,$3C
DB $66,$3C,$DB,$7E,$BD,$E7,$E7,$C3
DB $78,$30,$DC,$7C,$DE,$7F,$7B,$33
DB $01,$03,$03,$01,$07,$02,$1E,$04
DB $00,$00,$00,$00,$00,$00,$3C,$18
DB $66,$24,$C3,$42,$81,$81,$FF,$7E

; End of PE_CURSORTILES.Z80
